import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { X, Save } from "lucide-react";

export default function MaterialTakeoffModal({ lead, onClose, onSave }) {
  const [wastePercent, setWastePercent] = useState(15);
  const [calculating, setCalculating] = useState(false);

  const totalSqft = lead.total_sqft || lead.total_adjusted_sqft || 0;
  const pitch = lead.pitch_breakdown ? Object.keys(lead.pitch_breakdown)[0] : '4/12';
  
  // Calculate squares
  const squares = totalSqft / 100;
  
  // Calculate materials
  const wasteFactor = 1 + (wastePercent / 100);
  const shingleBundles = Math.ceil(squares * wasteFactor * 3);
  
  // Perimeter estimate (using sqrt approximation for typical roof)
  const estimatedPerimeter = Math.sqrt(totalSqft) * 4;
  const starterLinearFt = Math.ceil(estimatedPerimeter * 1.1);
  
  // Ridge cap (estimate 10% of perimeter)
  const ridgeCapLinearFt = Math.ceil(estimatedPerimeter * 0.1);
  
  // Underlayment (1 roll per 4 squares)
  const underlaymentRolls = Math.ceil(squares * wasteFactor / 4);
  
  // Ice & Water (1 roll per 200 sqft of perimeter area)
  const iceWaterRolls = Math.ceil(estimatedPerimeter * 3 / 200);
  
  // Drip Edge (perimeter)
  const dripEdgeLinearFt = Math.ceil(estimatedPerimeter);
  
  // Vents (1 per 300 sqft attic space)
  const vents = Math.ceil(totalSqft / 300);
  
  // Nails (1 box per 20 squares)
  const nailBoxes = Math.ceil(squares / 20);

  const materials = [
    { item: 'Architectural Shingles', quantity: shingleBundles, unit: 'Bundles' },
    { item: 'Starter Shingles', quantity: starterLinearFt, unit: 'Linear Ft' },
    { item: 'Ridge Cap Shingles', quantity: ridgeCapLinearFt, unit: 'Linear Ft' },
    { item: 'Synthetic Underlayment', quantity: underlaymentRolls, unit: 'Rolls' },
    { item: 'Ice & Water Shield', quantity: iceWaterRolls, unit: 'Rolls' },
    { item: 'Drip Edge', quantity: dripEdgeLinearFt, unit: 'Linear Ft' },
    { item: 'Ridge Vents', quantity: vents, unit: 'Units' },
    { item: 'Roofing Nails', quantity: nailBoxes, unit: 'Boxes' }
  ];

  const handleSaveToNotes = async () => {
    setCalculating(true);
    
    const timestamp = new Date().toLocaleString();
    const noteText = `
📋 AI Material Takeoff - ${timestamp}

Roof Size: ${totalSqft.toLocaleString()} sqft (${squares.toFixed(1)} squares)
Pitch: ${pitch}
Waste Factor: ${wastePercent}%

MATERIAL LIST:
${materials.map(m => `• ${m.item}: ${m.quantity} ${m.unit}`).join('\n')}

Generated by Aroof AI Takeoff
    `.trim();

    await onSave(noteText);
    setCalculating(false);
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <Card className="w-full max-w-3xl max-h-[90vh] overflow-y-auto">
        <CardContent className="p-8">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="text-2xl font-bold text-slate-900">✨ AI Material Takeoff</h2>
              <p className="text-slate-600 text-sm mt-1">
                {lead.customer_name} • {lead.property_address}
              </p>
            </div>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-slate-600 transition-colors"
            >
              <X className="w-6 h-6" />
            </button>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
            <div className="grid grid-cols-3 gap-4 text-center">
              <div>
                <p className="text-sm text-slate-600">Total Area</p>
                <p className="text-2xl font-bold text-blue-600">{totalSqft.toLocaleString()} sqft</p>
              </div>
              <div>
                <p className="text-sm text-slate-600">Squares</p>
                <p className="text-2xl font-bold text-blue-600">{squares.toFixed(1)}</p>
              </div>
              <div>
                <p className="text-sm text-slate-600">Pitch</p>
                <p className="text-2xl font-bold text-blue-600">{pitch}</p>
              </div>
            </div>
          </div>

          <div className="mb-6">
            <Label className="mb-2 block">Waste Factor</Label>
            <div className="flex items-center gap-4">
              <input
                type="range"
                min="10"
                max="25"
                value={wastePercent}
                onChange={(e) => setWastePercent(Number(e.target.value))}
                className="flex-1"
              />
              <span className="font-semibold text-lg w-16">{wastePercent}%</span>
            </div>
            <p className="text-xs text-slate-500 mt-1">
              Standard: 15% | Complex roof: 20-25%
            </p>
          </div>

          <div className="border border-slate-200 rounded-lg overflow-hidden mb-6">
            <table className="w-full">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700">Material</th>
                  <th className="px-4 py-3 text-right text-sm font-semibold text-slate-700">Quantity</th>
                  <th className="px-4 py-3 text-right text-sm font-semibold text-slate-700">Unit</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {materials.map((material, idx) => (
                  <tr key={idx} className="hover:bg-slate-50 transition-colors">
                    <td className="px-4 py-3 text-slate-900">{material.item}</td>
                    <td className="px-4 py-3 text-right font-semibold text-slate-900">{material.quantity}</td>
                    <td className="px-4 py-3 text-right text-slate-600">{material.unit}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
            <p className="text-xs text-yellow-800">
              ⚠️ These are estimated quantities based on standard formulas. Always verify measurements on-site and adjust for actual roof complexity, valleys, and waste.
            </p>
          </div>

          <div className="flex gap-3 justify-end">
            <Button variant="outline" onClick={onClose}>
              Close
            </Button>
            <Button 
              onClick={handleSaveToNotes}
              disabled={calculating}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {calculating ? (
                'Saving...'
              ) : (
                <>
                  <Save className="w-4 h-4 mr-2" />
                  Save to Notes
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}